/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faseslunaresiu;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author luis_
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cbxface = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        LbImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("faceslunares"));

        Cbxface.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecciona una occion", "nueva", "creciente ", "cuarto creciente", "llena", "gibosa meguante", "cuarto menguante", "menguante" }));
        Cbxface.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxfaceItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cbxface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cbxface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("imagen de la fase"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbxfaceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxfaceItemStateChanged
    
        String lugarImagen;
 

        int posicion = Cbxface.getSelectedIndex();

switch(posicion){
    case 0:
        break;
    case 1:
        lugarImagen="/imagenes/image0.jpg";
        URL url=this.getClass().getResource(lugarImagen);
        ImageIcon imagen0=new ImageIcon (url);
        LbImagen.setIcon(imagen0);
        break;
        
    case 2:
        lugarImagen="/imagenes/image1.jpg";
        URL url1=this.getClass(). getResource(lugarImagen);
        ImageIcon imagen1=new ImageIcon (url1);
        LbImagen.setIcon(imagen1);
        break;
        
    case 3:
        lugarImagen="/imagenes/image2.jpg";
        URL url2=this.getClass(). getResource(lugarImagen);
        ImageIcon imagen2=new ImageIcon (url2);
        LbImagen.setIcon(imagen2);
        break;
        
    case 4:
        lugarImagen="/imagenes/image3.jpg";
        URL url3=this.getClass(). getResource(lugarImagen);
        ImageIcon imagen3=new ImageIcon (url3);
        LbImagen.setIcon(imagen3);
        break;
        
    case 5:
        lugarImagen="/imagenes/image4.jpg";
        URL url4=this.getClass(). getResource(lugarImagen);
        ImageIcon imagen4=new ImageIcon (url4);
        LbImagen.setIcon(imagen4);
        break;
        
    case 6:
        lugarImagen="/imagenes/image5.jpg";
        URL url5=this.getClass(). getResource(lugarImagen);
        ImageIcon imagen5=new ImageIcon (url5);
        LbImagen.setIcon(imagen5);
        break;
        
    case 7:
        lugarImagen="/imagenes/image6.jpg";
        URL url6=this.getClass(). getResource(lugarImagen);
        ImageIcon imagen6=new ImageIcon (url6);
        LbImagen.setIcon(imagen6);
        break;
        
    case 8:
        lugarImagen="/imagenes/image7.jpg";
        URL url7=this.getClass(). getResource(lugarImagen);
        ImageIcon imagen7=new ImageIcon (url7);
        LbImagen.setIcon(imagen7);
        break;
        
    case 9:
        lugarImagen="/imagenes/image8.jpg";
        URL url8=this.getClass(). getResource(lugarImagen);
        ImageIcon imagen8=new ImageIcon (url8);
        LbImagen.setIcon(imagen8);
        break;
}
    }//GEN-LAST:event_CbxfaceItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbxface;
    private javax.swing.JLabel LbImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
