/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import basededatos.basededatos;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controlador.Controlador;
public class Cat_categoriaMVC extends javax.swing.JInternalFrame {

  
   Controlador c=new Controlador();

    String accion="";
    String vDescripcion="";
    Integer vId=0;
    

    /**
     * Creates new form Cat_categoria
     */
    public Cat_categoriaMVC() throws SQLException {
        initComponents();
        bloquear();
        cargar("");
    }
    
    void cargar_tabla(String valor) throws SQLException{
        
        DefaultTableModel tb = c.cargar_tabla_categoria(valor);
        tbDatos.setModel(tb);
        
        tbDatos.getColumnModel().getColumn(0).setPreferredWidth(0);
        tbDatos.getColumnModel().getColumn(1). setPreferredWidth(150);
    }

    void bloquear() {

        txtId.setEnabled(false);
        txtDescripcion.setEnabled(false);

        mIngresar.setEnabled(true);
        mModificar.setEnabled(true);
        mBorrar.setEnabled(true);
        mPreliminar.setEnabled(true);

        mGuardar.setEnabled(false);
        mCancelar.setEnabled(false);

        txtBuscar.setEnabled(true);
        btnBuscar.setEnabled(true);
    }

    void desbloquear() {
        txtId.setEnabled(false);
        txtDescripcion.setEditable(true);

        mIngresar.setEnabled(false);
        mModificar.setEnabled(false);
        mBorrar.setEnabled(false);
        mPreliminar.setEnabled(false);

        mGuardar.setEnabled(true);
        mCancelar.setEnabled(true);

        txtBuscar.setEnabled(false);
        btnBuscar.setEnabled(false);
    }

    void limpiar() {
        txtId.setText("");
        txtDescripcion.setText("");
    }

    public void cargar(String valor) {
        try {
            String[] titulos = {"Id", "Nombre de la Categloria"};
            String[] registros = new String[2];

            model = new DefaultTableModel(null, titulos);

            String cons = "Select categoria_id,descripcion from cat_categoria WHERE descripcion  LIKE '%" + valor + "%'";

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(cons);

            while (rs.next()) {
                registros[0] = rs.getString(1);
                registros[1] = rs.getString(2);
                model.addRow(registros);
            }
            tbDatos.setModel(model);
            
            tbDatos.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbDatos.getColumnModel().getColumn(1).setPreferredWidth(150);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
        private void mIngresarMouseClicked(java.awt.event.MouseEvent evt){
            accion="I";
            
            tbDatos.setEnabled(true);
            desbloquear();
            limpiar();
            txtDescripcion.requestFocus();
            generarId();
        }
        
             
              private void mGuardarMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        String vId, vDes;
//        Integer cons;

//        int id = Integer.parseInt(txtId.getText());
        String sql = "";
        
//        vId = txtId.getText();
        vDes = txtDescripcion.getText();
        
        if (accion=="I") {
            
            sql = "INSERT INTO cat_categoria (descripcion) VALUES (?)";
            try {
                PreparedStatement pst = cn.prepareStatement(sql);
                //pst.setString(1, vId);
                pst.setString(1, vDes);

                int n = pst.executeUpdate();
                if (n>0) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado con Exito");
                    bloquear();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Cat_categoriaMVC.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tbDatos.setEnabled(true);
        cargar("");
        bloquear();

    }         
             
             

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrool = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mIngresar = new javax.swing.JMenu();
        mModificar = new javax.swing.JMenu();
        mBorrar = new javax.swing.JMenu();
        mPreliminar = new javax.swing.JMenu();
        mGuardar = new javax.swing.JMenu();
        mCancelar = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("  Id:");

        jLabel2.setText("Descripcion");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setText("Buscar");

        btnBuscar.setText("Filtrar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrool.setViewportView(tbDatos);

        mIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingresar.png"))); // NOI18N
        mIngresar.setText("Ingresar");
        jMenuBar1.add(mIngresar);

        mModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modify.png"))); // NOI18N
        mModificar.setText("Modificar");
        jMenuBar1.add(mModificar);

        mBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        mBorrar.setText("Borrar");
        jMenuBar1.add(mBorrar);

        mPreliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/preview.png"))); // NOI18N
        mPreliminar.setText("Reporte");
        jMenuBar1.add(mPreliminar);

        mGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        mGuardar.setText("Guardar");
        jMenuBar1.add(mGuardar);

        mCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        mCancelar.setText("Cancelar");
        jMenuBar1.add(mCancelar);

        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        mSalir.setText("Salir");
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrool))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrool, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu mBorrar;
    private javax.swing.JMenu mCancelar;
    private javax.swing.JMenu mGuardar;
    private javax.swing.JMenu mIngresar;
    private javax.swing.JMenu mModificar;
    private javax.swing.JMenu mPreliminar;
    private javax.swing.JMenu mSalir;
    private javax.swing.JScrollPane scrool;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
