/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gif;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author luis_
 */
public class imagenes extends javax.swing.JFrame {

    /**
     * Creates new form imagenes
     */
    public imagenes() {
        initComponents();
        
       
    }
    public void Accion(){
        String LugarImagen;
        // imagen Normal
        if (chkChin.isSelected()){
            LugarImagen = "/ img/geek-----.gif";
            URL url=this.getClass().getResource(LugarImagen);
            ImageIcon imagen0=new ImageIcon (url);
            if (rootPaneCheckingEnabled) {
                
            }
            else
                
        }
    }
////    String lugarImagen;
////     public void selecionar(){
////          if(jCheckBox1.isSelected()){
////        lugarImagen="/img/geek-----.gif";
////        URL url=this.getClass().getResource(lugarImagen);
////        ImageIcon imagen0=new ImageIcon (url);
////        Lbimagen.setIcon(imagen0);
////           
////           
////       }else if(jCheckBox2.isSelected()){
////         lugarImagen="/img/geek--g--.gif";
////        URL url=this.getClass().getResource(lugarImagen);
////        ImageIcon imagen0=new ImageIcon (url);
////        Lbimagen.setIcon(imagen0);
////              
////          }else if(jCheckBox3.isSelected()){
////              
////        lugarImagen="/img/geek---h-.gif";
////        URL url=this.getClass().getResource(lugarImagen);
////        ImageIcon imagen0=new ImageIcon (url);
////        Lbimagen.setIcon(imagen0);
////          }else if(jCheckBox4.isSelected()){
////               lugarImagen="/img/geek----t.gif";
////        URL url=this.getClass().getResource(lugarImagen);
////        ImageIcon imagen0=new ImageIcon (url);
////        Lbimagen.setIcon(imagen0);
////              
////              
////              
////          }
////       
////    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        chkChin = new javax.swing.JCheckBox();
        chkGlasses = new javax.swing.JCheckBox();
        chkHair = new javax.swing.JCheckBox();
        chkTeeth = new javax.swing.JCheckBox();
        Lbimagen = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkChin.setText("chin");
        chkChin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkChinMouseClicked(evt);
            }
        });

        chkGlasses.setText("glasses");
        chkGlasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkGlassesMouseClicked(evt);
            }
        });
        chkGlasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGlassesActionPerformed(evt);
            }
        });

        chkHair.setText("hair");
        chkHair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkHairMouseClicked(evt);
            }
        });

        chkTeeth.setText("teeth");
        chkTeeth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkTeethMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkChin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkGlasses, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkHair, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTeeth, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(Lbimagen, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkChin)
                        .addGap(27, 27, 27)
                        .addComponent(chkGlasses)
                        .addGap(37, 37, 37)
                        .addComponent(chkHair)
                        .addGap(44, 44, 44)
                        .addComponent(chkTeeth))
                    .addComponent(Lbimagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkChinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkChinMouseClicked
       selecionar();
    }//GEN-LAST:event_chkChinMouseClicked

    private void chkGlassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGlassesActionPerformed
        selecionar();
    }//GEN-LAST:event_chkGlassesActionPerformed

    private void chkHairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkHairMouseClicked
        selecionar();
    }//GEN-LAST:event_chkHairMouseClicked

    private void chkTeethMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkTeethMouseClicked
        selecionar();
    }//GEN-LAST:event_chkTeethMouseClicked

    private void chkGlassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkGlassesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chkGlassesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new imagenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbimagen;
    private javax.swing.JCheckBox chkChin;
    private javax.swing.JCheckBox chkGlasses;
    private javax.swing.JCheckBox chkHair;
    private javax.swing.JCheckBox chkTeeth;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
